name: sandboxed_sandbox
description: "Playgrount to test Sandboxed features"
resolution: workspace
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  sandboxed: ^0.1.9
  sandboxed_core: ^0.1.6

  # features
  sandbox_feature:

  # packages
  flex_color_scheme: ^8.0.0
  google_fonts: ^8.0.1
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  
  build_runner: ^2.4.13
  sandboxed_generator: ^0.1.7

flutter:
  uses-material-design: true
