name: sandboxed
description: "A Flutter toolkit for building, testing, and presenting UI components in isolation with a focus on speed, modularity, and developer experience."
resolution: workspace
version: 0.1.7+2
homepage: https://sboxed.dev/
repository: https://github.com/sboxed/sandboxed
issue_tracker: https://github.com/sboxed/sandboxed/issues

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  sandboxed_core: ^0.1.5

  # ui
  google_fonts: ^8.0.1
  iconify_flutter_plus: ^1.0.0
  nested: ^1.0.0

  # routing
  # TODO(@melvspace): 03/20/25 auto_route dependency constraints usage of package
  auto_route: ^11.0.0

  # editor
  recursive_tree_flutter: ^1.0.0
  flutter_resizable_container: ^4.0.0
  two_dimensional_scrollables: ^0.3.0

  # persistence
  shared_preferences: ^2.0.0

  # component utility
  flutter_markdown_plus: ^1.0.0
  url_launcher: ^6.0.0

  # story params
  flex_color_picker: ^3.0.0

  # addons dependencies
  device_frame_plus: ^1.0.0

  # riverpod
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0

  # utility
  slugify: ^2.0.0
  freezed_annotation: ^3.1.0
  collection: ^1.18.0
  recase: ^4.0.0
  equatable: ^2.0.0
  markdown: ^7.0.0
  flat: ^0.5.0
  rxdart: ^0.28.0
  super_clipboard: ^0.9.1
  duration: ^4.0.0

  # internal
  sandboxed_ui_kit: ^0.1.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # test
  checks: ^0.3.0

  # code style
  flutter_lints:

  # generator
  build_runner: ^2.4.0
  freezed: ^3.2.0
  riverpod_generator: ^4.0.0+1
  auto_route_generator: ^10.4.0
  json_serializable: ^6.0.0
