name: sandboxed_library
description: "A new Flutter project."
resolution: workspace
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  sandboxed: ^0.1.9
  sandboxed_ui_kit: ^0.1.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

  build_runner: 
  sandboxed_generator: ^0.1.7+1

flutter:
  uses-material-design: true
