name: ui_book
description: "A new Flutter project."
resolution: workspace
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  sandboxed: ^0.1.9
  sandboxed_core: ^0.1.6

  ui_kit:
  products:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

  build_runner: ^2.4.13
  sandboxed_generator: ^0.1.7+1

flutter:
  uses-material-design: true
